//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComApplication.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int indexComPort_Speed {
            get {
                return ((int)(this["indexComPort_Speed"]));
            }
            set {
                this["indexComPort_Speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int indexComPort_Databits {
            get {
                return ((int)(this["indexComPort_Databits"]));
            }
            set {
                this["indexComPort_Databits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int indexComPort_Parity {
            get {
                return ((int)(this["indexComPort_Parity"]));
            }
            set {
                this["indexComPort_Parity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int indexComPort_StopBits {
            get {
                return ((int)(this["indexComPort_StopBits"]));
            }
            set {
                this["indexComPort_StopBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fileAnswerDefault {
            get {
                return ((string)(this["fileAnswerDefault"]));
            }
            set {
                this["fileAnswerDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fileAnswer {
            get {
                return ((string)(this["fileAnswer"]));
            }
            set {
                this["fileAnswer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string folderForDocDefault {
            get {
                return ((string)(this["folderForDocDefault"]));
            }
            set {
                this["folderForDocDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isAutoOpenSerial {
            get {
                return ((bool)(this["isAutoOpenSerial"]));
            }
            set {
                this["isAutoOpenSerial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isAutoOpenSerialDefault {
            get {
                return ((bool)(this["isAutoOpenSerialDefault"]));
            }
            set {
                this["isAutoOpenSerialDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string nameComPort {
            get {
                return ((string)(this["nameComPort"]));
            }
            set {
                this["nameComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int indexComPort_SpeedDefault {
            get {
                return ((int)(this["indexComPort_SpeedDefault"]));
            }
            set {
                this["indexComPort_SpeedDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int indexComPort_DatabitsDefault {
            get {
                return ((int)(this["indexComPort_DatabitsDefault"]));
            }
            set {
                this["indexComPort_DatabitsDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int indexComPort_ParityDefault {
            get {
                return ((int)(this["indexComPort_ParityDefault"]));
            }
            set {
                this["indexComPort_ParityDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int indexComPort_StopBitsDefault {
            get {
                return ((int)(this["indexComPort_StopBitsDefault"]));
            }
            set {
                this["indexComPort_StopBitsDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int razdByteIndex {
            get {
                return ((int)(this["razdByteIndex"]));
            }
            set {
                this["razdByteIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int razdByteIndexDefault {
            get {
                return ((int)(this["razdByteIndexDefault"]));
            }
            set {
                this["razdByteIndexDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isRadioButtonHexChecked {
            get {
                return ((bool)(this["isRadioButtonHexChecked"]));
            }
            set {
                this["isRadioButtonHexChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isRadioButtonHexCheckedDefault {
            get {
                return ((bool)(this["isRadioButtonHexCheckedDefault"]));
            }
            set {
                this["isRadioButtonHexCheckedDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isCheckBoxPeriodChecked {
            get {
                return ((bool)(this["isCheckBoxPeriodChecked"]));
            }
            set {
                this["isCheckBoxPeriodChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isCheckBoxPeriodCheckedDefault {
            get {
                return ((bool)(this["isCheckBoxPeriodCheckedDefault"]));
            }
            set {
                this["isCheckBoxPeriodCheckedDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isRazdPaketByPosledovSimbols {
            get {
                return ((bool)(this["isRazdPaketByPosledovSimbols"]));
            }
            set {
                this["isRazdPaketByPosledovSimbols"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isRazdPaketByPosledovSimbolsDefault {
            get {
                return ((bool)(this["isRazdPaketByPosledovSimbolsDefault"]));
            }
            set {
                this["isRazdPaketByPosledovSimbolsDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int timeAnswerWait {
            get {
                return ((int)(this["timeAnswerWait"]));
            }
            set {
                this["timeAnswerWait"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int timeAnswerWaitDefault {
            get {
                return ((int)(this["timeAnswerWaitDefault"]));
            }
            set {
                this["timeAnswerWaitDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isRazdHex8 {
            get {
                return ((bool)(this["isRazdHex8"]));
            }
            set {
                this["isRazdHex8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isRazdHex8Default {
            get {
                return ((bool)(this["isRazdHex8Default"]));
            }
            set {
                this["isRazdHex8Default"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int kolBytesPerLineIndex {
            get {
                return ((int)(this["kolBytesPerLineIndex"]));
            }
            set {
                this["kolBytesPerLineIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int kolBytesPerLineIndexDefault {
            get {
                return ((int)(this["kolBytesPerLineIndexDefault"]));
            }
            set {
                this["kolBytesPerLineIndexDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("139")]
        public int indexKodStranicaNomer {
            get {
                return ((int)(this["indexKodStranicaNomer"]));
            }
            set {
                this["indexKodStranicaNomer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("139")]
        public int indexKodStranicaNomerDefault {
            get {
                return ((int)(this["indexKodStranicaNomerDefault"]));
            }
            set {
                this["indexKodStranicaNomerDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int timeFormatIndex {
            get {
                return ((int)(this["timeFormatIndex"]));
            }
            set {
                this["timeFormatIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int timeFormatIndexDefault {
            get {
                return ((int)(this["timeFormatIndexDefault"]));
            }
            set {
                this["timeFormatIndexDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isTimeFormatPodpis {
            get {
                return ((bool)(this["isTimeFormatPodpis"]));
            }
            set {
                this["isTimeFormatPodpis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isTimeFormatPodpisDefault {
            get {
                return ((bool)(this["isTimeFormatPodpisDefault"]));
            }
            set {
                this["isTimeFormatPodpisDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int timerSendCommandInterval {
            get {
                return ((int)(this["timerSendCommandInterval"]));
            }
            set {
                this["timerSendCommandInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int timerSendCommandIntervalDefault {
            get {
                return ((int)(this["timerSendCommandIntervalDefault"]));
            }
            set {
                this["timerSendCommandIntervalDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fileCommandDefault {
            get {
                return ((string)(this["fileCommandDefault"]));
            }
            set {
                this["fileCommandDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fileCommand {
            get {
                return ((string)(this["fileCommand"]));
            }
            set {
                this["fileCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isRazdByte {
            get {
                return ((bool)(this["isRazdByte"]));
            }
            set {
                this["isRazdByte"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isRazdByteDefault {
            get {
                return ((bool)(this["isRazdByteDefault"]));
            }
            set {
                this["isRazdByteDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string simbolsRazdPaketByPosledovSimbols {
            get {
                return ((string)(this["simbolsRazdPaketByPosledovSimbols"]));
            }
            set {
                this["simbolsRazdPaketByPosledovSimbols"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13 10")]
        public string simbolsRazdPaketByPosledovSimbolsDefault {
            get {
                return ((string)(this["simbolsRazdPaketByPosledovSimbolsDefault"]));
            }
            set {
                this["simbolsRazdPaketByPosledovSimbolsDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("|")]
        public char razdHex8 {
            get {
                return ((char)(this["razdHex8"]));
            }
            set {
                this["razdHex8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int serialPort_WaitAnswer {
            get {
                return ((int)(this["serialPort_WaitAnswer"]));
            }
            set {
                this["serialPort_WaitAnswer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int serialPort_WaitAnswerDefault {
            get {
                return ((int)(this["serialPort_WaitAnswerDefault"]));
            }
            set {
                this["serialPort_WaitAnswerDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int serialPort_WaitWrite {
            get {
                return ((int)(this["serialPort_WaitWrite"]));
            }
            set {
                this["serialPort_WaitWrite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int serialPort_WaitWriteDefault {
            get {
                return ((int)(this["serialPort_WaitWriteDefault"]));
            }
            set {
                this["serialPort_WaitWriteDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isSerialPort_WaitAnswer {
            get {
                return ((bool)(this["isSerialPort_WaitAnswer"]));
            }
            set {
                this["isSerialPort_WaitAnswer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isSerialPort_WaitWrite {
            get {
                return ((bool)(this["isSerialPort_WaitWrite"]));
            }
            set {
                this["isSerialPort_WaitWrite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isSerialPort_WaitAnswerDefault {
            get {
                return ((bool)(this["isSerialPort_WaitAnswerDefault"]));
            }
            set {
                this["isSerialPort_WaitAnswerDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isSerialPort_WaitWriteDefault {
            get {
                return ((bool)(this["isSerialPort_WaitWriteDefault"]));
            }
            set {
                this["isSerialPort_WaitWriteDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isCheckConditionSerialPort {
            get {
                return ((bool)(this["isCheckConditionSerialPort"]));
            }
            set {
                this["isCheckConditionSerialPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isAddCRC {
            get {
                return ((bool)(this["isAddCRC"]));
            }
            set {
                this["isAddCRC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isShowColumnTime {
            get {
                return ((bool)(this["isShowColumnTime"]));
            }
            set {
                this["isShowColumnTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isShowColumnTimeDefault {
            get {
                return ((bool)(this["isShowColumnTimeDefault"]));
            }
            set {
                this["isShowColumnTimeDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isShowColumnHex {
            get {
                return ((bool)(this["isShowColumnHex"]));
            }
            set {
                this["isShowColumnHex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isShowColumnHexDefault {
            get {
                return ((bool)(this["isShowColumnHexDefault"]));
            }
            set {
                this["isShowColumnHexDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isShowColumnText {
            get {
                return ((bool)(this["isShowColumnText"]));
            }
            set {
                this["isShowColumnText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isShowColumnTextDefault {
            get {
                return ((bool)(this["isShowColumnTextDefault"]));
            }
            set {
                this["isShowColumnTextDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isShowTimeMS {
            get {
                return ((bool)(this["isShowTimeMS"]));
            }
            set {
                this["isShowTimeMS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isShowTimeMSDefault {
            get {
                return ((bool)(this["isShowTimeMSDefault"]));
            }
            set {
                this["isShowTimeMSDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int consolCommandTimeWidth {
            get {
                return ((int)(this["consolCommandTimeWidth"]));
            }
            set {
                this["consolCommandTimeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int consolCommandHexWidth {
            get {
                return ((int)(this["consolCommandHexWidth"]));
            }
            set {
                this["consolCommandHexWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int consolCommandTextWidth {
            get {
                return ((int)(this["consolCommandTextWidth"]));
            }
            set {
                this["consolCommandTextWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int consolAnswerTimeWidth {
            get {
                return ((int)(this["consolAnswerTimeWidth"]));
            }
            set {
                this["consolAnswerTimeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int consolAnswerHexWidth {
            get {
                return ((int)(this["consolAnswerHexWidth"]));
            }
            set {
                this["consolAnswerHexWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int consolAnswerTextWidth {
            get {
                return ((int)(this["consolAnswerTextWidth"]));
            }
            set {
                this["consolAnswerTextWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isAllowEnterText {
            get {
                return ((bool)(this["isAllowEnterText"]));
            }
            set {
                this["isAllowEnterText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isAllowEnterTextDefault {
            get {
                return ((bool)(this["isAllowEnterTextDefault"]));
            }
            set {
                this["isAllowEnterTextDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isDoubleCommandTextForm {
            get {
                return ((bool)(this["isDoubleCommandTextForm"]));
            }
            set {
                this["isDoubleCommandTextForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isDoubleCommandTextFormDefault {
            get {
                return ((bool)(this["isDoubleCommandTextFormDefault"]));
            }
            set {
                this["isDoubleCommandTextFormDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isShowSetSerialPort {
            get {
                return ((bool)(this["isShowSetSerialPort"]));
            }
            set {
                this["isShowSetSerialPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isShowSetSerialPortDefault {
            get {
                return ((bool)(this["isShowSetSerialPortDefault"]));
            }
            set {
                this["isShowSetSerialPortDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int mainFormStartLeft {
            get {
                return ((int)(this["mainFormStartLeft"]));
            }
            set {
                this["mainFormStartLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int mainFormStartLeftDefaul {
            get {
                return ((int)(this["mainFormStartLeftDefaul"]));
            }
            set {
                this["mainFormStartLeftDefaul"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int mainFormWidth {
            get {
                return ((int)(this["mainFormWidth"]));
            }
            set {
                this["mainFormWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int mainFormWidthDefault {
            get {
                return ((int)(this["mainFormWidthDefault"]));
            }
            set {
                this["mainFormWidthDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int mainFormHeight {
            get {
                return ((int)(this["mainFormHeight"]));
            }
            set {
                this["mainFormHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int mainFormHeightDefault {
            get {
                return ((int)(this["mainFormHeightDefault"]));
            }
            set {
                this["mainFormHeightDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int mainFormStartTop {
            get {
                return ((int)(this["mainFormStartTop"]));
            }
            set {
                this["mainFormStartTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int mainFormStartTopDefault {
            get {
                return ((int)(this["mainFormStartTopDefault"]));
            }
            set {
                this["mainFormStartTopDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isCheckConditionSerialPortDefault {
            get {
                return ((bool)(this["isCheckConditionSerialPortDefault"]));
            }
            set {
                this["isCheckConditionSerialPortDefault"] = value;
            }
        }
    }
}
